In [3]:
mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]]
print(type(mat))
print(mat[2][0]) #Se voglio accedere, ad esempio, all'elemente "10"

<class 'list'>
10


In [15]:
import math
print(math.sin(90))
print(math.cos(180))
print(math.factorial(10))
print(math.pi) # Pi greco

0.8939966636005579
-0.5984600690578581
3628800
3.141592653589793


In [17]:
print(math.degrees(math.pi))
# la funzione .degrees transorma gli angoli da radianti a gradi
# di fatti l'angolo del pi greco è 180°

180.0


In [37]:
import numpy as np
import statistics as st
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = np.array(lst)
print(lst)
print(f"Vendita massima mensile: {max(lst)}") #vendita massima 
print(f"Vendita minima mensile: {min(lst)}") #vendita minima
n = 0
print("\nVendite mensili maggiori di 5000 oggetti: ")
for numero in lst:
    if numero > 5000:
        n += 1
        print(numero)
print(f"Numero di mesi con vendite maggiori di 5000 oggetti: {n}")

print("\nVendite mensili minori di 3000 oggetti: ")
for numero in lst:
    if numero < 3000:
        print(numero)
print(f"Media di oggetti mensili venduti: {st.mean(lst)}") #la funzione mean di statistics fa la media di un insieme di valori, tra cui anche una lista

[2000 5500 7200 4320 1280 1900 2500 3900 6410 8150 7100 5350]
Vendita massima mensile: 8150
Vendita minima mensile: 1280

Vendite mensili maggiori di 5000 oggetti: 
5500
7200
6410
8150
7100
5350
Numero di mesi con vendite maggiori di 5000 oggetti: 6

Vendite mensili minori di 3000 oggetti: 
2000
1280
1900
2500
Media di oggetti mensili venduti: 4634


In [49]:
import pandas as pd
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

print(fatturati_dict[1997]) 
print(fatturati_series[1997])

# Possiamo osseravare che sono due tipologie di dato diversi 
print(type(fatturati_dict))
print(type(fatturati_series))

# A colpo d'occhio inesperto la differenza è a livello grafico. Sicuramente più intuitivo la series dal punto di vista di analisi dei dati partendo da un grafico

12000
12000
<class 'dict'>
<class 'pandas.core.series.Series'>


In [68]:
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] )
print(stipendi)

for i in range(len(stipendi)):
    stipendi[i] = stipendi[i] * 2
print(stipendi)

[ 100  200  300  400  500  600  700  800  900 1000]
[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [70]:
import numpy as np

stipendi = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])
print(stipendi)
stipendi_doppi = stipendi * 2

print(stipendi_doppi)

[ 100  200  300  400  500  600  700  800  900 1000]
[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [96]:
# es:
# Scrivere un programma che, data una lista di numeri, fornisca in output i tre numeri più grandi; gestire il caso in cui la lista sia più corta di tre, 
# e quando uno o più dei numeri selezionati sono uguali.
numeri = []
while True:
    numero = input("Inserisci un numero (digita 'stop' per fermarti): ")
    if numero.lower() == "stop":
        break
    try:
        numero = int(numero)
        numeri.append(numero)
    except ValueError:
        print("Devi inserire un numero intero!")

# Rimuove duplicati e ordina in ordine decrescente
numeri_unici = sorted(set(numeri), reverse=True)
print(numeri_unici)
# Controlla quanti numeri unici ci sono
if len(numeri_unici) == 0:
    print("Nessun numero inserito.")
elif len(numeri_unici) <= 3:
    print(f"I numeri più grandi (senza duplicati) sono: {numeri_unici}")
else:
    print(f"I tre numeri più grandi (senza duplicati) sono: {numeri_unici[:3]}")


    
    


Inserisci un numero (digita 'stop' per fermarti):  


Devi inserire un numero intero!


Inserisci un numero (digita 'stop' per fermarti):  stop


[]
Nessun numero inserito.


In [105]:
import statistics as stat
numeri = []
numeri_maggiori_K = []
while True:
    numero = input("Inserisci un numero (digita 'stop' per fermarti): ")
    if numero.lower() == "stop":
        break
    try:
        numero = int(numero)
        numeri.append(numero)
    except ValueError:
        print("Devi inserire un numero intero!")

K = input("Inserisci il numero di paragone: ")
try:
    K = int(K)
except ValueError:
    print("Devi inserire un numero intero! ")
for numero in numeri:
    if numero > K:
        numeri_maggiori_K.append(numero)
if len(numeri_maggiori_K) == 0:
    print(f"Non hai inserito numeri maggiori di {K} e non posso eseguire la media ")
else:
    media = stat.mean(numeri_maggiori_K)
    print(f"La lista dei numeri che hai composto: {numeri}")
    print(f"Il numero di paragone che hai scelto: {K}")
    print(f"I numeri maggiori di {K} presi per la media: {numeri_maggiori_K}")
    print(f"La loro media è: {media}")


Inserisci un numero (digita 'stop' per fermarti):  10
Inserisci un numero (digita 'stop' per fermarti):  10
Inserisci un numero (digita 'stop' per fermarti):  50
Inserisci un numero (digita 'stop' per fermarti):  40
Inserisci un numero (digita 'stop' per fermarti):  0
Inserisci un numero (digita 'stop' per fermarti):  30
Inserisci un numero (digita 'stop' per fermarti):  50
Inserisci un numero (digita 'stop' per fermarti):  stop
Inserisci il numero di paragone:  90


Non hai inserito numeri maggiori di 90 e non posso eseguire la media 


In [109]:
numeri = []
while True:
    numero = input("Inserisci un numero (digita 'stop' per fermarti): ")
    if numero.lower() == "stop":
        break
    try:
        numero = int(numero)
        numeri.append(numero)
    except ValueError:
        print("Devi inserire un numero intero!")
print(f"La tua lista: {numeri}\n")
for numero in numeri:
    print("*"*numero)

Inserisci un numero (digita 'stop' per fermarti):  


Devi inserire un numero intero!


Inserisci un numero (digita 'stop' per fermarti):  5
Inserisci un numero (digita 'stop' per fermarti):  2
Inserisci un numero (digita 'stop' per fermarti):  3
Inserisci un numero (digita 'stop' per fermarti):  4
Inserisci un numero (digita 'stop' per fermarti):  stop


La tua lista: [5, 2, 3, 4]

*****
**
***
****


In [122]:
lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]
codici_con_95 = []
for codice in lista_cf:
    if "95" in codice:
        codici_con_95.append(codice)
for codice in codici_con_95:
    print(f"Codice Fiscale: {codice}\nCaratteri del nome: {codice[:3]}\nCaratteri del cognome: {codice[3:6]}\n")

Codice Fiscale: ABCDEF95G01A123B
Caratteri del nome: ABC
Caratteri del cognome: DEF

Codice Fiscale: STUVWX95Z04A654E
Caratteri del nome: STU
Caratteri del cognome: VWX

Codice Fiscale: DEFGHI95J06A987G
Caratteri del nome: DEF
Caratteri del cognome: GHI



In [140]:
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"]
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"]
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]
alunni_prima_edizione = []

for i in range(len(edizioni)):
    if edizioni[i] == 1:
        alunni_prima_edizione.append(studenti[i])
print("Studenti in una prima edizione:")
for alunno in alunni_prima_edizione:
    print(f"{alunno}")


Studenti in una prima edizione:
Alex
Faith


In [159]:
prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"]
prezzi_corretti = []

for prezzo in prezzi:
    prezzi_corretti.append(prezzo.replace("€","$"))
print(prezzi_corretti)

#Lo stesso esericizio è possibile farlo con la lista comprehension
prezzi_comprehension = [prezzo.replace("€","$") for prezzo in prezzi]
print(prezzi_comprehension)
    

['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']
['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [164]:
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"]
squadra_uno = [nome for nome in studenti if studenti.index(nome) % 2 == 0]
squadra_due = [nome for nome in studenti if studenti.index(nome) % 2 != 0]

print(squadra_uno)
print(squadra_due)

['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
['Bob', 'Dan', 'Faith', 'Henry', 'John']


In [197]:
import statistics as stat
guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50]
tmp = 0
for i in range(len(guadagni)):
    tmp += guadagni[i]
    media_precedente = media
    media = tmp / (i + 1)
    if (i + 1) == 1:
        print(f"Mese {i+1}: €{media:.2f}")
    else:
        if media > media_precedente:
            print(f"Mese {i+1}: €{media:.2f} (media prec: €{media_precedente:.2f} - il guadagno è maggiore)")
        elif media < media_precedente:
            print(f"Mese {i+1}: €{media:.2f} (media prec: €{media_precedente:.2f} - il guadagno è minore)")





Mese 1: €100.00
Mese 2: €95.00 (media prec: €100.00 - il guadagno è minore)
Mese 3: €86.67 (media prec: €95.00 - il guadagno è minore)
Mese 4: €75.00 (media prec: €86.67 - il guadagno è minore)
Mese 5: €70.00 (media prec: €75.00 - il guadagno è minore)
Mese 6: €71.67 (media prec: €70.00 - il guadagno è maggiore)
Mese 7: €74.29 (media prec: €71.67 - il guadagno è maggiore)
Mese 8: €80.00 (media prec: €74.29 - il guadagno è maggiore)
Mese 10: €74.00 (media prec: €80.00 - il guadagno è minore)
Mese 11: €71.82 (media prec: €74.00 - il guadagno è minore)
Mese 12: €70.00 (media prec: €71.82 - il guadagno è minore)
